# Constants_Sequences_and_Random_Values

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2017, 11, 22)

In [3]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
tf.__version__

'1.4.0'

In [5]:
np.__version__

'1.13.3'

In [6]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Constant Value Tensors

Q1. Create a tensor of the shape [2, 3] with all elements set to zero.


In [14]:
a1 = tf.zeros((2, 3))
print(a1.eval())

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Q2. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to zero.

In [15]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])
a2 = tf.zeros(X.shape)
print(a2.eval())

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Q3. Create a tensor of shape [2, 3] with all elements set to one.

In [16]:
a3 = tf.ones((2, 3))
print(a3.eval())

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


Q4. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to one.

In [17]:
a4 = tf.ones(X.shape)
print(a4.eval())

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


Q5. Create a tensor of the shape [3, 2], with all elements of 5.

In [18]:
a5 = tf.fill((3, 2), 5)
print(a5.eval())

[[5 5]
 [5 5]
 [5 5]]


Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]], with dtype=float32

In [19]:
a6 = tf.constant([[1, 3, 5], [4, 6, 8]], dtype=tf.float32)
print(a6.eval())

[[ 1.  3.  5.]
 [ 4.  6.  8.]]


Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.

In [20]:
a7 = tf.fill((2, 3), 4)
print(a7.eval())

[[4 4 4]
 [4 4 4]]


## Sequences

Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.

In [22]:
a8 = tf.linspace(5., 10., 50)
print(a8.eval())

[  5.           5.10204077   5.20408154   5.3061223    5.40816307
   5.51020432   5.61224508   5.71428585   5.81632662   5.91836739
   6.02040815   6.12244892   6.22448969   6.32653046   6.4285717
   6.53061247   6.63265324   6.734694     6.83673477   6.93877554
   7.04081631   7.14285755   7.24489784   7.34693909   7.44897938
   7.55102062   7.65306139   7.75510216   7.85714293   7.95918369
   8.06122494   8.16326523   8.26530647   8.36734676   8.46938801
   8.5714283    8.67346954   8.77551079   8.87755108   8.97959232
   9.08163261   9.18367386   9.2857151    9.38775539   9.48979568
   9.59183693   9.69387817   9.79591846   9.89795876  10.        ]


Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].

In [24]:
# a9 = tf.linspace(10, 100, 2) --- wrong. linspace takes only float for start and stop, not int
a9 = tf.range(10, 101, 2)
print(a9.eval())

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


## Random Tensors

Q10. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=2.

In [25]:
a10 = tf.random_normal(mean=0, stddev=2, shape=(3, 2))
print(a10.eval())

[[ 3.21540499  2.66623545]
 [-1.45691085 -1.2112937 ]
 [-2.24828053  1.5942806 ]]


Q11. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 such that any values don't exceed 2 standard deviations from the mean.

In [27]:
a11 = tf.truncated_normal(mean=0, stddev=1, shape=(3, 2))
print(a11.eval())

[[-0.38115388  0.19936337]
 [-0.14589146 -1.39185703]
 [-1.00375259 -0.11078193]]


Q12. Create a random tensor of the shape [3, 2], with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).

In [28]:
a12 = tf.random_uniform(minval=0, maxval=2, shape=(3, 2))
print(a12.eval())

[[ 1.55806756  1.53567076]
 [ 1.74306393  0.36756635]
 [ 0.27877522  0.43297124]]


Q13. Let X be a tensor of [[1, 2], [3, 4], [5, 6]]. Shuffle X along its first dimension.

In [31]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])
a13 = tf.random_shuffle(X)
print(a13.eval())

[[3 4]
 [5 6]
 [1 2]]


Q14. Let X be a random tensor of the shape [10, 10, 3], with elements from a unit normal distribution. Crop X with the shape of [5, 5, 3].

In [34]:
X = tf.random_normal(shape=(10, 10, 3))
a14 = tf.random_crop(X, size=(5, 5, 3))
print(a14.eval())

[[[ 1.14402604 -0.62351418  0.2422165 ]
  [ 1.05063772 -1.06093419 -1.00732088]
  [ 0.14243208  0.93399346  0.93698823]
  [ 0.90916491 -0.70058697  0.08573756]
  [-0.72408855  1.48768592  1.23318374]]

 [[ 0.68918437  1.29115486  1.15048385]
  [-1.56838584  1.28913736 -0.62288272]
  [ 0.70327419 -0.0057831   0.16081724]
  [ 1.20221138 -0.40473771 -0.77810156]
  [ 2.16424203  0.06472711  0.91669834]]

 [[ 0.12797712 -0.06184929 -1.08140647]
  [-0.11985153  0.15957062 -0.33569929]
  [ 1.03865218 -0.06196605  0.70852965]
  [ 0.30192626 -0.19390054 -1.29442525]
  [ 1.02150953  0.27433383  0.63033408]]

 [[-0.42718416  0.27063724 -0.95045227]
  [ 0.7663781   1.20648336 -2.08629274]
  [-0.5994426  -0.21424364 -0.49621177]
  [-1.84249592 -0.15695331  0.79659396]
  [-0.09782646  0.77555293  0.20229769]]

 [[-0.34470299  0.16070578 -0.86076337]
  [-1.03234124 -0.44877473 -0.04472819]
  [-0.83858639  0.83704722  0.36654928]
  [ 0.90531719  1.50715435  0.06397521]
  [-0.78819412  1.407511    0.48